### PR TITLE
fix(lint): disable eslint nuxt.config.js extend line

### PR DESCRIPTION
**Pull request by zalog**
`config` and `ctx` are not used, I think it would be ok if we disable eslint on this line.

### CODE REVIEW

**Comment by Atinux** [comment]
I think we can remove extends and add a line in the comments block to https://nuxtjs.org/api/configuration-build/

**Comment by zalog** [comment]
Tnks for your time guys.
Ok @Atinux , I'll come back with a commit soon.

**Comment by zalog** [comment]
Sorry @clarkdo I'm not sure how can I do that, can you be more specific please? :)

**Comment by NickBolles** [comment]
this is already fixed as part of #449

**Pull request merged**
