### PR TITLE
chore: bump nuxt version

### PR DESCRIPTION
**Pull request by aldarund**

### CODE REVIEW

**Comment by aldarund** [comment]
@clarkdo its so that new users dont ask why i used CNA and i have in package.json 2.0.0 instead of latest one

**Comment by clarkdo** [comment]
I prefer sending them to `semver` site. 😅

**Comment by aldarund** [comment]
thats a point, but there another questions that they ask so its just to minimize it.
Whatever, do as you feel better, its not important issue to discuss it much :)

**Comment by manniL** [comment]
Agree with @clarkdo here. Better educate the user about NPM constraints and semver instead (maybe directly write a FAQ in the README?)

**Comment by aldarund** [comment]
I`m afraid the user who ask such question dont read readme :)

**Comment by manniL** [comment]
Could be :man_shrugging: but that should not be part of our scope.

**Comment by pi0** [comment]
Some suggestion: We may show a message after setup you created a project using latest nuxt x.y.z

**Comment by clarkdo** [comment]
I’ll add the message

**Pull request closed without merging**
