### PR TITLE
features selection

### PR DESCRIPTION
**Pull request by sascha245**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Add features selection similar to vue-cli 3:
  - Typescript
  - PWA
  - Linter (if selected, eslint by default and tslint if typescript is selected)
  - Prettier

Solves #23 and in some parts #42

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @sascha245 

Thanks for the PR, I am waiting for others approval for the TS part.

But it's looking great so far for me and like the checkboxes option :)

**Comment by aldarund** [comment]
LGTM

**Comment by hartmut-co-uk** [comment]
+ the README file might need to be updated to reflect the new features?
@Atinux where's the main documentation for `create-nuxt-app` supposed to be? 
How are the README.md of this repo & https://github.com/nuxt/docs/blob/master/en/guide/installation.md kept 'in sync'? I guess just manually?

**Comment by kevinmarrec** [comment]
Alright, first, thanks @sascha245 for the PR !

I suggest indeed (as @hartmut-co-uk said) to wait for my next iteration which will likely change things around this PR, so that's better IMO to wait and I'll review it.

This PR uses `nuxt-ts` and `nuxt-tslint` packages which will be replaced by the `ts-loader` + `fork-ts-checker-webpack-plugin` combination.

**Comment by sascha245** [comment]
Yep, in that case it would indeed be better to wait. 
Tell me when the new version is out so that I can make the necessary changes ;-)

**Comment by kevinmarrec** [comment]
I agree with @hartmut-co-uk that it would be easier to add the TS options on `create-nuxt-app` on a separate PR, so that other options (PWA, eslint + prettier) get merged directly.

It can also be hard to track everything when a PR implements too many different things 😁

**Comment by sascha245** [comment]
Note that I didn't implement eslint and prettier myself, I just transformed the separated yes/no questions to checkboxes.

Anyway, I created a new and clean pull request (#156) containing only pwa, eslint, prettier and axios checkboxes.
I will add TS and TSLint support once again in a separate PR when the new Nuxt version is out.
Hope that makes things easier for you.

With this, I will close this pull request.

**Pull request closed without merging**
