### PR TITLE
feat: upgrade Ava

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] Upgraded ava from `1.x` to `2.x` which brings lots of breaking changes.

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
> Thanks for the pr, it looks good, the conflict needs to be resolved.

Resolved conflicts

**Comment by vinayakkulkarni** [comment]
@clarkdo : any thoughts on merging this?

**Comment by clarkdo** [comment]
Sorry for the delay due to my device issue, I’ll check this as soon as it’s back to work

**Comment by vinayakkulkarni** [comment]
@clarkdo it's cool 😎

**Comment by vinayakkulkarni** [comment]
Uhh. Hi!

**Pull request merged**
