### PR TITLE
feat: add support for semantic-pull-requests

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] enables support for [semantic-pull-requests](https://github.com/probot/semantic-pull-requests)

like `commitlint`, this ensures the PR title is correct.

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
Need to enable this GitHub app: https://probot.github.io/apps/semantic-pull-requests/

**Comment by clarkdo** [comment]
It seemed that I don't have the permission for installing app.

@Atinux @pi0 Please review

**Comment by vinayakkulkarni** [comment]
//cc @Atinux & @pi0

**Comment by vinayakkulkarni** [comment]
@Atinux or @pi0 any chance of this being merged?

**Comment by vinayakkulkarni** [comment]
bump.

@Atinux  / @pi0

**Comment by Atinux** [comment]
Sorry for the delay @vinayakkulkarni

**Pull request merged**
