### PR TITLE
Added iview to UI framework

### PR DESCRIPTION
**Pull request by EstebanFuentealba**
Add [iview](https://www.iviewui.com/) #83

### CODE REVIEW

**Comment by hartmut-co-uk** [comment]
+1

**Comment by gahabeen** [comment]
Can't pick `iview` on `npx create-nuxt-app <app> --edge`. Any idea why?

**Comment by manniL** [comment]
Not released yet.

**Comment by hartmut-co-uk** [comment]
@gahabeen you may use `npx github:nuxt/create-nuxt-app yourname --edge` if you want to use latest master version (vs. latest stable release).
_Note: you need to use up/down keys in UI framework selection to scroll to the full list - as only a subset is revealed._

**Pull request merged**
