### PR TITLE
feat(cli): use cac for cli

### PR DESCRIPTION
**Pull request by evillt**
```console
$ yarn create nuxt-app --help
...
success Installed "create-nuxt-app@2.7.1" with binaries:
      - create-nuxt-app
> Generating Nuxt.js project in /Users/evila/--help
? Project name (--help) 
```

The `target path` is `/User/evila/--help` obviously not right 🤔

### CODE REVIEW

**Comment by clarkdo** [comment]
@evillt Thank you for the pr, I'm curious that what's the reason for choosing cac, is there any benefit comparing with commander or minimalist ?

**Comment by evillt** [comment]
CAC is very similar to commander.

The main reason is SAO already taken CAC as a dependency([you can see here](https://github.com/saojs/sao/blob/master/package.json#L23)), reuse a node-module to keep `create-nuxt-app` the same download size.

How do you think 🤔

**Comment by clarkdo** [comment]
Thanks

**Comment by evillt** [comment]
It would be honer 💃

**Pull request merged**
