### PR TITLE
feat(template): remove dotenv module

### PR DESCRIPTION
**Pull request by clarkdo**
As @Atinux has mentioned in discord, we should remove dotenv module from create-nuxt-app now.

### CODE REVIEW

**Comment by web2033** [comment]
Can we know why?

**Comment by Atinux** [comment]
@web2033 this is related to the fact that Nuxt v2.13 will directly support `.env` and `runtimeConfig`, see https://github.com/nuxt/nuxt.js/pull/7312

Actually `@nuxtjs/dotenv` actually bring a security vulnerability for people adding secret keys in `.env` that will be forwarded to the Webpack bundle and then exposed to the end users.

**Comment by Atinux** [comment]
Why we removed the @nuxtjs/dotenv module

**Comment by web2033** [comment]
@Atinux I think you meant this -> https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config

**Pull request merged**
