### PR TITLE
chore(cna-template): fix error when switching layouts

### PR DESCRIPTION
**Pull request by paulocuambe**
The error below is thrown whenever a page that has a custom layout is loaded coming from a page using the default layout:

```
Invalid component name: "layouts/default.vue". Component names should conform to valid custom element name in html5 specification.
```

The way to solve this is by giving the **default.vue** component a name attribute as described in this [comment](https://github.com/nuxt/nuxt.js/issues/7133#issuecomment-621292621)

This PR ensures that the component is ready for layout switches.

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]

**Review by Atinux — APPROVED** [review]

**Comment by paulocuambe** [comment]
Hi @pi0, can review this PR and give it a foolow up?

Thanks in advance.

**Comment by pi0** [comment]
@paulocuambe Thanks for PR but i guess this is a bug in nuxt! We cannot fix bugs by adding workaround to CNA.

**Comment by paulocuambe** [comment]
Being honest I don't understand how this is a problem in Nuxt itself. I'm closing the PR, hope the problem might be solved soon.

**Comment by manniL** [comment]
> 
> 
> Being honest I don't understand how this is a problem in Nuxt itself. I'm closing the PR, hope the problem might be solved soon.

Because the name of layout and page components is a valid name (with respect to the html5 specs) by default.

**Comment by paulocuambe** [comment]
Thank you, @manniL.
Looking forward to contributing to the framework in the future.

**Comment by pi0** [comment]
@paulocuambe Would you please open an issue on nuxt repository to track this? 🙏

**Pull request closed without merging**
