### PR TITLE
chore: update @nuxtjs/eslint-module

### PR DESCRIPTION
**Pull request by ricardogobbosouza**

### CODE REVIEW

**Comment by manniL** [comment]
Not necessary IMO as `^0.X.Y` always includes all versions starting with `0.`

**Comment by ricardogobbosouza** [comment]
@manniL You're right!

**Comment by manniL** [comment]
I was wrong here :see_no_evil: 	
This doesn't apply to < v1 versions, so
`^0.1.Y` won't over everything starting with 0 but only everything starting with `0.1`.

**Comment by ricardogobbosouza** [comment]
@manniL truth :grin:
I'm going to release `v1.0.0`, I think it's stable now

**Comment by manniL** [comment]
:+1: 	
Feel free to update the deps here then :relaxed:

**Pull request closed without merging**
