### PR TITLE
fix: Fix TypeScript build error.

### PR DESCRIPTION
**Pull request by 282Haniwa**
To build with TypeScript, you need ts-loader.
That's why I added ts-loader to package.json.

### CODE REVIEW

**Comment by clarkdo** [comment]
@282Haniwa `ts-loader` is a dependency of [`@nuxt/typescript-build`](https://github.com/nuxt/typescript/blob/c144f279a234cc6fcbc78b625af2f151c3518d58/packages/typescript-build/package.json#L20)

**Review by clarkdo — COMMENTED** [review]
@282Haniwa `ts-loader` is a dependency of [`@nuxt/typescript-build`](https://github.com/nuxt/typescript/blob/c144f279a234cc6fcbc78b625af2f151c3518d58/packages/typescript-build/package.json#L20)

**Comment by pi0** [comment]
Agree with @clarkdo. This should be fixed with last release 😊

**Comment by 282Haniwa** [comment]
Thank you for your support.

**Pull request closed without merging**
