### PR TITLE
feat(create-nuxt-app): add --overwrite-dir flag

### PR DESCRIPTION
**Pull request by jamesgeorge007**
https://github.com/nuxt/create-nuxt-app/pull/778#issuecomment-849063461
cc @clarkdo

### CODE REVIEW

**Review by clarkdo — COMMENTED** [review]
Nice.

Can you update readme ?

**Review by clarkdo — APPROVED** [review]

**Comment by TroyOtto** [comment]
can I use an example of this flag?

**Comment by clarkdo** [comment]
According to [readme](https://github.com/nuxt/create-nuxt-app#--overwrite-dir)

```
 npx create-nuxt-app  ./ --overwrite-dir
```

**Comment by AllanOricil** [comment]
@clarkdo you did an amazing job. Thanks for that.

**Pull request merged**
